"""add movimento, nivel, pontos

Revision ID: 87b6b4c1e66c
Revises: 
Create Date: 2025-11-26 10:47:47.904775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b6b4c1e66c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nivel', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pontos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pontos')
    op.drop_column('users', 'nivel')
    # ### end Alembic commands ###
